/**
 * End-to-end test that drives a REAL Godot process instead of mocking it.
 *
 * Every other test in this directory exercises the Node-side server in
 * isolation (unit tests calling into GodotBridge / tool handlers directly).
 * None of them ever prove that a tool call actually reaches the Godot
 * editor and mutates a project on disk. This test closes that gap for one
 * representative flow: create a scene, add a node to it, and confirm the
 * .tscn file on disk actually contains that node.
 *
 * Approach: editor-plugin headless, not the runtime autoload.
 * -------------------------------------------------------------------------
 * Editor-only tools like `add_node` and `create_scene` are handled by
 * addons/godot_mcp/tool_executor.gd, which only runs inside the EditorPlugin
 * (addons/godot_mcp/plugin.gd). The runtime autoload (mcp_runtime.gd) only
 * exposes a small "runtime" tool surface (query_runtime_node, send_input,
 * take_screenshot, ...) meant for inspecting a *running game*, not editing
 * scenes on disk — so it can't be used to test add_node.
 *
 * The open question was whether an EditorPlugin can run at all under
 * `--headless`. It can: Godot supports `--headless --editor`, which runs
 * the full editor (including plugin _enter_tree/_enable_plugin) without a
 * display server. This was confirmed manually before writing this test —
 * launching the fixture project with `--headless --editor` produces
 * "[Godot MCP] Plugin loading..." / "[MCP] Connected to server" in stdout.
 * So this test uses that mode directly.
 *
 * The addon's WebSocket client (mcp_client.gd) hardcodes ws://127.0.0.1:6505
 * with no override, so the bridge in this test must also listen on the
 * real DEFAULT_PORT rather than a private test port — that's the one way
 * this test can collide with a real godot-mcp-server already running on
 * this machine. If port 6505 is already taken, the test skips instead of
 * failing.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync, readFileSync, rmSync, cpSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { GodotBridge, createBridge } from '../godot-bridge.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// The full GUI exe, NOT the _console.exe sibling (a broken 0.2MB stub that dies with
// CreateProcess error 193). Set GODOT_BIN to your Godot executable to run this
// suite; without it, existsSync('') is false and everything below skips.
const GODOT_BIN = process.env.GODOT_BIN ?? '';
const FIXTURE_PROJECT = join(__dirname, 'fixtures', 'e2e-project');
const SCENE_PATH = 'res://e2e_test_scene.tscn';
const SCENE_FILE = join(FIXTURE_PROJECT, 'e2e_test_scene.tscn');

const CONNECT_TIMEOUT_MS = 30000;
const BRIDGE_PORT = 6505; // hardcoded in addons/godot_mcp/mcp_client.gd — not configurable

const godotAvailable = existsSync(GODOT_BIN);

/**
 * Port 6505 is hardcoded into the addon and can't be overridden, so if a
 * real godot-mcp-server (e.g. the user's own editor session) already owns
 * it, we can't bind our test bridge there. Rather than fail the suite in
 * that case, we detect it up front and skip with a clear reason.
 */
async function isPortFree(port: number): Promise<boolean> {
  const probe = createBridge(port);
  try {
    await probe.start();
    probe.stop();
    return true;
  } catch {
    return false;
  }
}

/**
 * Copy the repo's addon over the fixture's own copy before the editor starts.
 *
 * The fixture project carries its own `addons/godot_mcp`, and the editor this
 * suite spawns loads THAT one. Without this sync the tests silently exercise
 * whatever was in the fixture last time — which happened while writing these
 * tests: a just-fixed clobbering bug still failed here because the editor was
 * running the stale copy, which reads exactly like "the fix didn't work".
 * scripts/test-gd.ps1 and CI already mirror the addon for the same reason; the
 * Node suite has to do it too or it is testing a different codebase.
 */
function syncAddonIntoFixture(): void {
  const source = join(__dirname, '..', '..', '..', 'addons', 'godot_mcp');
  const dest = join(FIXTURE_PROJECT, 'addons', 'godot_mcp');
  if (!existsSync(source)) return;
  rmSync(dest, { recursive: true, force: true });
  cpSync(source, dest, {
    recursive: true,
    // .uid files are per-project and regenerated by the editor; copying them
    // across makes Godot complain about duplicate UIDs.
    filter: (src) => !src.endsWith('.uid'),
  });
}

const portFree = godotAvailable ? await isPortFree(BRIDGE_PORT) : false;
const canRun = godotAvailable && portFree;

describe.skipIf(!canRun)('E2E — real Godot editor process', () => {
  let bridge: GodotBridge;
  let godotProcess: ChildProcess | null = null;

  beforeAll(async () => {
    if (existsSync(SCENE_FILE)) rmSync(SCENE_FILE);
    syncAddonIntoFixture();

    bridge = createBridge(BRIDGE_PORT);
    await bridge.start();

    godotProcess = spawn(
      GODOT_BIN,
      ['--headless', '--editor', '--path', FIXTURE_PROJECT],
      { stdio: 'ignore' }
    );

    await new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => {
        reject(new Error(`Godot editor did not connect to the bridge within ${CONNECT_TIMEOUT_MS}ms`));
      }, CONNECT_TIMEOUT_MS);

      const check = setInterval(() => {
        if (bridge.isConnected()) {
          clearInterval(check);
          clearTimeout(timer);
          resolve();
        }
      }, 250);
    });

    // CRITICAL: confirm we're talking to the fixture project and not to
    // somebody's real one.
    //
    // The addon hardcodes port 6505, so ANY Godot editor already open on this
    // machine will reconnect to whatever is listening there — including the
    // bridge this test just started. The isPortFree() check above only proves
    // the port was free when the suite loaded; it cannot stop an existing
    // editor from attaching a moment later. Without this guard the mutation
    // tests below run `create_scene`/`add_node`/`remove_node` against that
    // editor's project. That has actually happened, and it wrote a scene file
    // into a real game project.
    const connectedPath = bridge.getStatus().projectPath ?? '';
    const expected = FIXTURE_PROJECT.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
    const actual = connectedPath.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
    if (actual !== expected) {
      throw new Error(
        `Refusing to run: the editor on port ${BRIDGE_PORT} has "${connectedPath}" open, not the test fixture ` +
        `("${FIXTURE_PROJECT}"). Close other Godot editors before running the e2e suite — these tests create and ` +
        `delete scenes in whatever project is connected.`
      );
    }
  }, CONNECT_TIMEOUT_MS + 5000);

  afterAll(() => {
    godotProcess?.kill();
    godotProcess = null;
    bridge?.stop();
    if (existsSync(SCENE_FILE)) rmSync(SCENE_FILE);
  });

  it('connects a real Godot editor over the WebSocket bridge', () => {
    expect(bridge.isConnected()).toBe(true);
  });

  it('creates a scene, adds a node, and persists it to disk', async () => {
    const createResult = await bridge.invokeTool('create_scene', {
      scene_path: SCENE_PATH,
      root_node_type: 'Node2D',
      root_node_name: 'Root',
    }) as Record<string, unknown>;
    expect(createResult.scene_path ?? SCENE_PATH).toBeTruthy();
    expect(existsSync(SCENE_FILE)).toBe(true);

    await bridge.invokeTool('add_node', {
      scene_path: SCENE_PATH,
      node_name: 'E2ESprite',
      node_type: 'Sprite2D',
      parent_path: '.',
    });

    const contents = readFileSync(SCENE_FILE, 'utf-8');
    expect(contents).toContain('E2ESprite');
    expect(contents).toContain('Sprite2D');
  }, 15000);

  it('removes the node it added', async () => {
    const result = await bridge.invokeTool('remove_node', {
      scene_path: SCENE_PATH,
      node_path: 'E2ESprite',
    }) as Record<string, unknown>;
    expect(result).toBeTruthy();

    const contents = readFileSync(SCENE_FILE, 'utf-8');
    expect(contents).not.toContain('E2ESprite');
  }, 15000);

  // -------------------------------------------------------------------------
  // Live-scene harness
  // -------------------------------------------------------------------------
  // Everything above drives the DISK path. The live path — the scene is open in
  // the editor, so tools mutate the editor's real node tree instead of a loaded
  // copy — is the half that carries the project's hardest invariants, and until
  // now nothing tested it automatically:
  //
  //   * `_discard_scene` is a NO-OP on a live scene, so a tool that writes and
  //     then fails validation leaves those writes applied while reporting
  //     failure. That exact shape has been found six times.
  //   * A live edit must NOT touch the .tscn on disk (that's the anti-clobber
  //     guarantee the README leads with).
  //
  // These run against a real headless editor with the scene actually open.
  describe('live scene (open in the editor)', () => {
    const LIVE_SCENE = 'res://e2e_live_scene.tscn';
    const LIVE_FILE = join(FIXTURE_PROJECT, 'e2e_live_scene.tscn');

    beforeAll(async () => {
      if (existsSync(LIVE_FILE)) rmSync(LIVE_FILE);
      await bridge.invokeTool('create_scene', {
        scene_path: LIVE_SCENE,
        root_node_type: 'Node2D',
        root_node_name: 'Root',
      });
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE,
        node_name: 'Body',
        node_type: 'CharacterBody2D',
        parent_path: '.',
      });
      // set_material_3d needs a node that actually has material_override, or it
      // fails on the type check before writing anything and the case proves
      // nothing.
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE,
        node_name: 'Mesh',
        node_type: 'MeshInstance3D',
        parent_path: '.',
      });
      // Nodes the clobber cases need: a Sprite2D for texture/material, a Control
      // for anchor presets.
      const EXTRA_NODES = [
        ['Sprite', 'Sprite2D'],
        ['Panel', 'Control'],
        ['Shape', 'CollisionShape2D'], // the node that actually carries `shape`
      ] as const;
      for (const [name, type] of EXTRA_NODES) {
        await bridge.invokeTool('add_node', {
          scene_path: LIVE_SCENE, node_name: name, node_type: type, parent_path: '.',
        });
      }
      // connect_signal refuses unless the receiving script really declares the
      // method, so the probe script declares it and is attached to the receiver.
      await bridge.invokeTool('create_script', {
        path: 'res://e2e_clobber_probe.gd',
        content: 'extends Node2D\nfunc _on_body_ready() -> void:\n\tpass\n',
      });
      await bridge.invokeTool('attach_script', {
        scene_path: LIVE_SCENE, node_path: '.', script_path: 'res://e2e_clobber_probe.gd',
      });
      await bridge.invokeTool('create_scene', {
        scene_path: 'res://e2e_clobber_child.tscn',
        root_node_type: 'Node2D',
        root_node_name: 'Child',
      });
      // A .tres texture, not a .png: an image needs Godot's import step, which a
      // freshly-spawned headless editor has not necessarily finished, and the
      // texture case would fail for a reason that has nothing to do with it.
      await bridge.invokeTool('create_resource', {
        resource_type: 'GradientTexture1D',
        resource_path: 'res://e2e_clobber_tex.tres',
      });
      // These three files were written a moment ago through the bridge, so the
      // editor's filesystem doesn't know about them yet and load() fails —
      // `instance_scene` came back with "Failed to instantiate scene" on a cold
      // CI runner while passing locally purely on timing. Rescan and wait for the
      // scene to actually be loadable rather than sleeping a guessed interval.
      // A scan may already be running right after those writes, and rescan
      // rejects rather than queueing — so the request itself is best-effort. The
      // poll below is the actual wait: it stops when the scene is loadable.
      await bridge.invokeTool('rescan_filesystem', {}).catch(() => null);
      for (let i = 0; i < 40; i++) {
        const probe = await bridge.invokeTool('read_scene', {
          scene_path: 'res://e2e_clobber_child.tscn',
        }).catch(() => null) as Record<string, unknown> | null;
        if (probe && !probe.error) break;
        await new Promise(r => setTimeout(r, 250));
      }
      // From here on the scene is OPEN, so every tool below takes the live path.
      await bridge.invokeTool('open_in_godot', { path: LIVE_SCENE });
    }, 30000);

    afterAll(() => {
      if (existsSync(LIVE_FILE)) rmSync(LIVE_FILE);
      for (const extra of [
        'e2e_clobber_probe.gd', 'e2e_clobber_probe.gd.uid',
        'e2e_clobber_child.tscn', 'e2e_clobber_tex.tres',
      ]) {
        const f = join(FIXTURE_PROJECT, extra);
        if (existsSync(f)) rmSync(f);
      }
    });

    it('edits the live tree without touching the file on disk', async () => {
      const before = readFileSync(LIVE_FILE, 'utf-8');

      await bridge.invokeTool('add_raycast', {
        scene_path: LIVE_SCENE,
        parent_path: '.',
        node_name: 'LiveRay',
        dimension: '2D',
      });

      const dump = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(dump).toContain('LiveRay');
      // The whole point: the agent's edit lives in the editor, unsaved, so the
      // developer's own unsaved work is never overwritten.
      expect(readFileSync(LIVE_FILE, 'utf-8')).toBe(before);
    }, 20000);

    it('undoes a live edit through the editor history', async () => {
      const undone = await bridge.invokeTool('undo_last', {}) as Record<string, unknown>;
      expect(String(undone.message ?? '')).toContain('LiveRay');

      const dump = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(dump).not.toContain('LiveRay');
    }, 20000);

    // The regression net for the six-times bug. Each case takes several settable
    // values and rejects the LAST one, so a tool that writes as it goes leaves
    // the earlier writes behind.
    //
    // Each case names its own `probe`: a LIVE-AWARE read of the state the tool
    // touches. Comparing scene_tree_dump alone is not enough and this was proven
    // the hard way — the first version of this harness compared only the tree,
    // and passed with the bug deliberately reintroduced into set_physics_layers,
    // because a changed property doesn't show up in a structural dump.
    const PARTIAL_WRITE_CASES: Array<{
      tool: string;
      args: Record<string, unknown>;
      probe: { tool: string; args: Record<string, unknown> };
    }> = [
      {
        tool: 'set_physics_layers',
        // Valid layer, then a collision_mask naming a layer that doesn't exist.
        args: { node_path: 'Body', collision_layer: 3, collision_mask: ['no_such_layer_xyz'] },
        probe: { tool: 'get_collision_info', args: { node_path: 'Body' } },
      },
      {
        tool: 'set_material_3d',
        // Applies metallic/roughness, then rejects the emission colour.
        args: { node_path: 'Mesh', metallic: 0.5, roughness: 0.5, emission_color: 'not-a-color' },
        probe: { tool: 'get_scene_node_properties', args: { node_path: 'Mesh' } },
      },
      {
        tool: 'setup_environment',
        // This one CREATES a WorldEnvironment node before validating colours, so
        // the structural dump is the right probe here.
        args: { sky_top_color: { r: 1, g: 1, b: 1, a: 1 }, fog_enabled: true, sky_horizon_color: 'not-a-color' },
        probe: { tool: 'scene_tree_dump', args: {} },
      },
    ];

    it.each(PARTIAL_WRITE_CASES)(
      '$tool leaves nothing behind when a later argument is invalid',
      async ({ tool, args, probe }) => {
        const readState = async () => JSON.stringify(
          await bridge.invokeTool(probe.tool, { scene_path: LIVE_SCENE, ...probe.args }),
        );

        const fileBefore = readFileSync(LIVE_FILE, 'utf-8');
        const treeBefore = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
        const stateBefore = await readState();

        let failed = false;
        try {
          const res = await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }) as Record<string, unknown>;
          failed = res?.ok === false || typeof res?.error === 'string';
        } catch {
          failed = true; // an error result surfaces as a throw through the bridge
        }
        expect(failed, `${tool} was expected to reject its last argument`).toBe(true);

        expect(await readState(), `${tool} left a partial write (probe: ${probe.tool})`).toBe(stateBefore);
        expect(JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }))).toBe(treeBefore);
        expect(readFileSync(LIVE_FILE, 'utf-8')).toBe(fileBefore);
      },
      25000,
    );

    // The anti-clobber guarantee, which is the first thing the README claims.
    //
    // A tool that loads the scene from disk, mutates the copy and saves it does
    // two destructive things at once when the scene is open: it discards
    // whatever is unsaved in the editor, and the reload that follows the save
    // wipes the live tree. Confirmed by hand against a real project before this
    // test existed — an `attach_script` call destroyed an unsaved node that was
    // sitting in the open scene.
    //
    // `holder` is a node added to the LIVE tree and never saved. Any tool that
    // round-trips through disk will lose it.
    // Every scene-mutating tool that reaches the disk. Arguments are chosen to
    // SUCCEED: a tool that errors early would never load the scene, so the test
    // would pass without proving anything.
    const CLOBBER_TOOLS: Array<{ tool: string; args: Record<string, unknown> }> = [
      { tool: 'attach_script', args: { node_path: 'Body', script_path: 'res://e2e_clobber_probe.gd' } },
      { tool: 'detach_script', args: { node_path: 'Body' } },
      { tool: 'set_node_groups', args: { node_path: 'Body', groups: ['e2e_group'] } },
      { tool: 'set_collision_shape', args: { node_path: 'Shape', shape_type: 'RectangleShape2D' } },
      { tool: 'set_sprite_texture', args: { node_path: 'Sprite', texture_type: 'FromPath', texture_params: { path: 'res://e2e_clobber_tex.tres' } } },
      { tool: 'set_mesh', args: { node_path: 'Mesh', mesh_type: 'BoxMesh' } },
      { tool: 'set_material', args: { node_path: 'Mesh', material_type: 'StandardMaterial3D' } },
      { tool: 'set_anchor_preset', args: { node_path: 'Panel', preset: 'full_rect' } },
      { tool: 'snap_node_to_grid', args: { node_path: 'Mesh', grid_size: 16 } },
      { tool: 'set_scene_node_property', args: { node_path: 'Body', property_name: 'visible', value: false } },
      { tool: 'instance_scene', args: { parent_path: '.', instance_path: 'res://e2e_clobber_child.tscn', instance_name: 'Inst' } },
      { tool: 'connect_signal', args: { from_node: 'Body', signal: 'ready', to_node: '.', method: '_on_body_ready' } },
      { tool: 'disconnect_signal', args: { from_node: 'Body', signal: 'ready', to_node: '.', method: '_on_body_ready' } },
      // Runs after set_collision_shape, which is what puts a shape on Shape.
      { tool: 'set_resource_property', args: { node_path: 'Shape', resource_path: 'shape', property_name: 'size', value: { x: 16, y: 16 } } },
    ];

    it.each(CLOBBER_TOOLS)('$tool does not destroy unsaved work in the open scene', async ({ tool, args }) => {
      const holder = `Unsaved_${tool}`;
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE, node_name: holder, node_type: 'Node2D', parent_path: '.',
      });
      const withHolder = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(withHolder, 'setup failed: the unsaved node never reached the live tree').toContain(holder);

      // The call must actually do its job. Tolerating an error here would let a
      // tool that bails out before touching the scene pass vacuously.
      const res = await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }) as Record<string, unknown>;
      expect(res?.error, `${tool} failed, so this case proves nothing: ${JSON.stringify(res)}`).toBeUndefined();

      const after = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(after, `${tool} clobbered unsaved live work`).toContain(holder);

      await bridge.invokeTool('remove_node', { scene_path: LIVE_SCENE, node_path: holder }).catch(() => {});
    }, 25000);

    // Reads have to see the live tree too. A tool that loads from disk reports
    // the last-SAVED state, so an agent that edits and then reads back gets
    // stale values with no way to tell — it looks like the edit silently failed.
    const LIVE_READ_TOOLS: Array<{ tool: string; args: Record<string, unknown>; expect: string }> = [
      { tool: 'read_scene', args: {}, expect: 'ReadProbe' },
      { tool: 'get_scene_hierarchy', args: {}, expect: 'ReadProbe' },
      { tool: 'get_scene_node_properties', args: { node_path: 'ReadProbe' }, expect: 'position' },
      { tool: 'get_node_groups', args: { node_path: 'ReadProbe' }, expect: 'read_probe_group' },
      { tool: 'find_nodes_in_group', args: { group: 'read_probe_group' }, expect: 'ReadProbe' },
    ];

    it.each(LIVE_READ_TOOLS)('$tool reads the live tree, not the last save', async ({ tool, args, expect: needle }) => {
      // Added and grouped only in the editor — never saved to the .tscn.
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE, node_name: 'ReadProbe', node_type: 'Node2D', parent_path: '.',
      });
      await bridge.invokeTool('set_node_groups', {
        scene_path: LIVE_SCENE, node_path: 'ReadProbe', groups: ['read_probe_group'],
      });
      expect(readFileSync(LIVE_FILE, 'utf-8'), 'setup: the probe must NOT be on disk').not.toContain('ReadProbe');

      const out = JSON.stringify(await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }));
      expect(out, `${tool} returned last-saved state instead of the live tree`).toContain(needle);

      await bridge.invokeTool('remove_node', { scene_path: LIVE_SCENE, node_path: 'ReadProbe' }).catch(() => {});
    }, 25000);

    // The build-and-verify loop. A live edit stays in the editor by design, so
    // without a way to persist it an agent that edits an open scene and then
    // launches the game tests the PREVIOUS version of the file — which is
    // exactly what happened with a HUD that reported ok and was not there.
    it('save_scene writes a live edit to disk', async () => {
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE, node_name: 'SaveProbe', node_type: 'Node2D', parent_path: '.',
      });

      // Precondition: the edit exists in the editor and NOT on disk.
      const treeBefore = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(treeBefore).toContain('SaveProbe');
      expect(readFileSync(LIVE_FILE, 'utf-8')).not.toContain('SaveProbe');

      const saved = await bridge.invokeTool('save_scene', { scene_path: LIVE_SCENE }) as Record<string, unknown>;
      expect(saved.error).toBeUndefined();
      expect(saved.changed).toBe(true);

      expect(readFileSync(LIVE_FILE, 'utf-8'), 'save_scene did not persist the live edit').toContain('SaveProbe');

      // Saving again is a no-op rather than an error, and says so.
      const again = await bridge.invokeTool('save_scene', { scene_path: LIVE_SCENE }) as Record<string, unknown>;
      expect(again.error).toBeUndefined();
      expect(again.changed).toBe(false);

      await bridge.invokeTool('remove_node', { scene_path: LIVE_SCENE, node_path: 'SaveProbe' });
      await bridge.invokeTool('save_scene', { scene_path: LIVE_SCENE });
      expect(readFileSync(LIVE_FILE, 'utf-8')).not.toContain('SaveProbe');
    }, 30000);

    it('save_scene refuses a scene that is not open, and says why', async () => {
      const res = await bridge.invokeTool('save_scene', {
        scene_path: 'res://e2e_clobber_child.tscn',
      }).catch((e: Error) => ({ error: e.message })) as Record<string, unknown>;
      // A closed scene is already on disk — the error has to say that rather
      // than looking like a failure the agent should retry.
      expect(String(res.error ?? '')).toMatch(/not open/i);
    }, 20000);

    // The open P0: in a real project an instanced child came back with
    // `script = null` written over its inherited script, and the player silently
    // stopped moving. The disk path does NOT reproduce it (there is a passing
    // GDScript test), which leaves the LIVE path as the suspect — that scene was
    // open, remove_node reported live_editor_scene: true, and a save followed.
    //
    // Checked on the live tree first, because the file is only written when the
    // editor saves; then through a real save, because that is where the override
    // would be serialised.
    it('an instanced child keeps its script through live edits and a save', async () => {
      const CHILD_SCRIPT = 'res://e2e_inst_child.gd';
      const CHILD = 'res://e2e_inst_child.tscn';
      const PARENT = 'res://e2e_inst_parent.tscn';
      const PARENT_FILE = join(FIXTURE_PROJECT, 'e2e_inst_parent.tscn');
      const LEFTOVERS = ['e2e_inst_child.gd', 'e2e_inst_child.gd.uid',
                         'e2e_inst_child.tscn', 'e2e_inst_parent.tscn'];
      // Clean at the START too: a run that fails mid-way never reaches its own
      // cleanup, and the next run then dies on "File already exists" — an error
      // about the previous failure, not the current one.
      const sweep = () => {
        for (const f of LEFTOVERS) {
          const p2 = join(FIXTURE_PROJECT, f);
          if (existsSync(p2)) rmSync(p2);
        }
      };
      sweep();

      await bridge.invokeTool('create_script', {
        path: CHILD_SCRIPT,
        content: 'extends Node2D\n\nfunc _physics_process(_d: float) -> void:\n\tpass\n',
      });
      await bridge.invokeTool('create_scene', {
        scene_path: CHILD, root_node_type: 'Node2D', root_node_name: 'Child',
      });
      await bridge.invokeTool('attach_script', {
        scene_path: CHILD, node_path: '.', script_path: CHILD_SCRIPT,
      });
      await bridge.invokeTool('create_scene', {
        scene_path: PARENT, root_node_type: 'Node2D', root_node_name: 'Parent',
      });
      // The editor has to know about the child scene before it can be instanced.
      await bridge.invokeTool('rescan_filesystem', {}).catch(() => null);
      for (let i = 0; i < 40; i++) {
        const probe = await bridge.invokeTool('read_scene', { scene_path: CHILD }).catch(() => null);
        if (probe && !(probe as Record<string, unknown>).error) break;
        await new Promise(r => setTimeout(r, 250));
      }
      await bridge.invokeTool('instance_scene', {
        scene_path: PARENT, instance_path: CHILD, node_name: 'Kid',
      });

      // Now open it, so every mutation below takes the LIVE path.
      await bridge.invokeTool('open_in_godot', { path: PARENT });

      const scriptOf = async () => {
        const tree = await bridge.invokeTool('read_scene', { scene_path: PARENT }) as Record<string, unknown>;
        const kids = ((tree.root as Record<string, unknown>)?.children ?? []) as Array<Record<string, unknown>>;
        return kids.find(k => k.name === 'Kid')?.script ?? null;
      };

      expect(await scriptOf(), 'setup: the instance should carry its inherited script').toContain('e2e_inst_child.gd');

      // The sequence from the incident: sibling added and removed on the live
      // tree, then a save.
      await bridge.invokeTool('add_node', {
        scene_path: PARENT, node_name: 'Marker', node_type: 'Marker2D', parent_path: '.',
      });
      expect(await scriptOf(), 'script lost after a live add_node').toContain('e2e_inst_child.gd');

      await bridge.invokeTool('remove_node', { scene_path: PARENT, node_path: 'Marker' });
      expect(await scriptOf(), 'script lost after a live remove_node').toContain('e2e_inst_child.gd');

      await bridge.invokeTool('set_node_properties', {
        scene_path: PARENT, node_path: 'Kid', properties: { position: { x: 10, y: 20 } },
      });
      expect(await scriptOf(), 'script lost after setting a property on the instance').toContain('e2e_inst_child.gd');

      await bridge.invokeTool('save_scene', { scene_path: PARENT });

      // The actual symptom: `script = null` serialised as an instance override.
      const onDisk = readFileSync(PARENT_FILE, 'utf-8');
      expect(onDisk, 'script = null was written over the inherited script').not.toContain('script = null');
      expect(onDisk).toContain('instance=ExtResource');
      expect(await scriptOf(), 'script lost after the save').toContain('e2e_inst_child.gd');

      await bridge.invokeTool('close_scene_tab', { scene_path: PARENT, force: true }).catch(() => null);
      sweep();
    }, 45000);

    it('reverts a whole batch when one operation fails', async () => {
      const treeBefore = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));

      try {
        await bridge.invokeTool('batch_scene_edit', {
          scene_path: LIVE_SCENE,
          stop_on_error: true,
          operations: [
            { op: 'add_node', node_name: 'BatchLiveA', node_type: 'Node2D', parent_path: '.' },
            { op: 'add_node', node_name: 'BatchLiveB', node_type: 'Node2D', parent_path: '.' },
            { op: 'remove_node', node_path: 'NoSuchNode' },
          ],
        });
      } catch {
        // expected: the batch reports failure
      }

      // "batch discarded, nothing saved" has to be true on the live path too,
      // where _discard_scene cannot undo anything.
      const treeAfter = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(treeAfter).toBe(treeBefore);
    }, 25000);
  });

  /**
   * Tools that only exist because there is an editor: they read or drive
   * EditorInterface. The headless GDScript suite runs without an EditorPlugin,
   * so these can only be exercised here — and until now they were the tools with
   * no automated coverage at all.
   */
  describe('editor-only tools', () => {
    const SEL_SCENE = 'res://e2e_editor_only.tscn';
    const SEL_FILE = join(FIXTURE_PROJECT, 'e2e_editor_only.tscn');

    beforeAll(async () => {
      // create_scene refuses to overwrite, so a leftover from a previous run
      // would fail the whole block in beforeAll.
      if (existsSync(SEL_FILE)) rmSync(SEL_FILE);
      await bridge.invokeTool('create_scene', {
        scene_path: SEL_SCENE,
        root_node_type: 'Node2D',
        root_node_name: 'Root',
      });
      for (const name of ['Alpha', 'Beta']) {
        await bridge.invokeTool('add_node', {
          scene_path: SEL_SCENE, node_name: name, node_type: 'Node2D', parent_path: '.',
        });
      }
      // Selection acts on the OPEN scene, so it has to be open.
      await bridge.invokeTool('open_in_godot', { path: SEL_SCENE });
      await new Promise((r) => setTimeout(r, 1500));
    }, 40000);

    it('selects nodes, reports the selection, and clears it', async () => {
      // scene_path is required and must match the scene actually open: the tool
      // refuses to select into a scene the developer is not looking at.
      await bridge.invokeTool('select_nodes', { scene_path: SEL_SCENE, node_paths: ['Alpha', 'Beta'] });
      const selected = JSON.stringify(await bridge.invokeTool('get_editor_selection', {}));
      expect(selected).toContain('Alpha');
      expect(selected).toContain('Beta');

      await bridge.invokeTool('clear_editor_selection', {});
      const cleared = JSON.stringify(await bridge.invokeTool('get_editor_selection', {}));
      expect(cleared).not.toContain('Alpha');
    }, 25000);

    it('closes the scene tab it opened', async () => {
      // force: the scene is dirty from being opened and edited; without it the
      // tool refuses rather than discarding the developer's unsaved work, which
      // is the behaviour worth having.
      const closed = JSON.stringify(await bridge.invokeTool('close_scene_tab', {
        scene_path: SEL_SCENE, force: true,
      }));
      expect(closed).toContain(SEL_SCENE);

      // With the scene closed, a read has to fall back to the disk path and
      // still work — the dual-path contract in reverse.
      const read = JSON.stringify(await bridge.invokeTool('read_scene', { scene_path: SEL_SCENE }));
      expect(read).toContain('Alpha');
    }, 25000);

    it('reports export presets without needing templates installed', async () => {
      // export_project itself needs export templates, which a CI runner does not
      // have; what IS checkable is that the preset reader answers honestly
      // rather than throwing. A fixture with no presets must say so.
      const presets = JSON.stringify(await bridge.invokeTool('list_export_presets', {}));
      expect(presets).toMatch(/presets|count/);
    }, 25000);
  });

  // -------------------------------------------------------------------------
  // Runtime awareness — the half that only exists with a game actually running
  // -------------------------------------------------------------------------
  /**
   * The activity feed has two sources the editor alone cannot produce: the
   * runtime autoload, which is the only thing that can see its own scene being
   * swapped, and the editor's debugger session, which is the only thing that can
   * see the game die. Both were shipped covered by source inspection alone,
   * because nothing in this harness had ever launched a game.
   *
   * These launch one. If the events do not actually reach the bridge, the whole
   * feature is decorative and every other test would still pass.
   */
  describe('activity from a running game', () => {
    const RUN_SCENE = 'res://e2e_run_scene.tscn';
    const RUN_FILE = join(FIXTURE_PROJECT, 'e2e_run_scene.tscn');

    /** Collect pushed activity events while `body` runs. */
    async function captureActivity(body: () => Promise<void>): Promise<Record<string, unknown>[]> {
      const seen: Record<string, unknown>[] = [];
      const collect = (e: Record<string, unknown>) => { seen.push(e); };
      bridge.onEditorActivity(collect);
      try {
        await body();
      } finally {
        bridge.offEditorActivity(collect);
      }
      return seen;
    }

    afterAll(async () => {
      // Never leave a game running: it holds the runtime slot on the bridge and
      // the next suite would look like "the game is already playing".
      try { await bridge.invokeTool('stop_scene', {}); } catch { /* already stopped */ }
      if (existsSync(RUN_FILE)) rmSync(RUN_FILE);
    });

    /**
     * One launch-to-stop cycle, captured whole.
     *
     * Deliberately a single test rather than three. The first version split it
     * into "it starts", "it is running", "it stops" and let each lean on the
     * game the previous one had left alive — which passed on the machine it was
     * written on and failed on the next one, because there the game exited on
     * its own partway through. A launched game is not state a later test may
     * assume; anything that needs one launches it.
     */
    it('reports the game starting and stopping', async () => {
      await bridge.invokeTool('create_scene', {
        scene_path: RUN_SCENE, root_node_type: 'Node2D', root_node_name: 'RunRoot',
      });

      const events = await captureActivity(async () => {
        await bridge.invokeTool('run_scene', {
          scene: RUN_SCENE, wait_for_runtime: true, startup_timeout_ms: 20000,
        });
        // Both sides push, so this is a settle window rather than a poll.
        await new Promise((r) => setTimeout(r, 2000));
        await bridge.invokeTool('stop_scene', {});
        await new Promise((r) => setTimeout(r, 2000));
      });

      const runtime = events.filter((e) => e.source === 'runtime');
      // Naming what did arrive makes a failure diagnosable instead of just "none".
      const types = runtime.map((e) => String(e.type));
      const seen = types.join(', ') || '(none)';

      expect(runtime.length, `runtime events seen: ${seen}`).toBeGreaterThan(0);

      // game_started comes from the autoload, game_running from the debugger
      // watch. Either proves the push path; requiring a specific one would make
      // this depend on which lands first.
      expect(seen).toMatch(/game_started|game_running/);

      // Only the editor can report this — a dead game cannot announce its own
      // death, which is the whole reason the debugger watch exists.
      expect(seen, `runtime events seen: ${seen}`).toContain('game_stopped');

      // None of it may be filed as the agent's own work, or the feed drops it
      // before the agent ever sees it.
      expect(runtime.every((e) => e.source !== 'agent')).toBe(true);
    }, 60000);

    it('names the scene the game is running, not just that one changed', async () => {
      // The detail is the point: telling an agent "the scene changed" without
      // saying to what leaves it knowing its node paths are stale and nothing
      // else. This comes from the autoload, which is the only side that sees it.
      const events = await captureActivity(async () => {
        await bridge.invokeTool('run_scene', {
          scene: RUN_SCENE, wait_for_runtime: true, startup_timeout_ms: 20000,
        });
        await new Promise((r) => setTimeout(r, 2000));
        await bridge.invokeTool('stop_scene', {});
      });

      const withScene = events.find(
        (e) => e.source === 'runtime' && typeof e.detail === 'string' && String(e.detail).endsWith('.tscn')
      );
      const seen = events.filter((e) => e.source === 'runtime')
        .map((e) => `${e.type}=${JSON.stringify(e.detail)}`).join(', ') || '(none)';
      expect(withScene, `runtime events seen: ${seen}`).toBeDefined();
      expect(String(withScene?.detail)).toContain('e2e_run_scene.tscn');
    }, 60000);
  });

  /**
   * The deterministic-testing tools, against a real running game.
   *
   * These resolve over frames from inside the game's own _physics_process, so
   * nothing headless can tell whether they actually answer — the failure mode is
   * a call that never returns, which every other kind of test reports as a pass.
   */
  describe('deterministic testing tools', () => {
    const DET_SCENE = 'res://e2e_det_scene.tscn';
    const DET_FILE = join(FIXTURE_PROJECT, 'e2e_det_scene.tscn');

    beforeAll(async () => {
      // run_scene refuses while a scene is already playing, and the previous
      // suite's game may still be shutting down. Without this every test below
      // fails with "runtime not connected", which points at the wrong thing.
      await bridge.invokeTool('stop_scene', {}).catch(() => undefined);
      await new Promise((r) => setTimeout(r, 1500));

      await bridge.invokeTool('create_scene', {
        scene_path: DET_SCENE, root_node_type: 'Node2D', root_node_name: 'DetRoot',
      });
      const launched = await bridge.invokeTool('run_scene', {
        scene: DET_SCENE, wait_for_runtime: true, startup_timeout_ms: 20000,
      }) as Record<string, unknown>;
      // Fail here, with the launch result, rather than seven times downstream.
      if (!launched.runtime_connected) {
        throw new Error(`the game did not come up: ${JSON.stringify(launched)}`);
      }
    }, 60000);

    afterAll(async () => {
      try { await bridge.invokeTool('time_scale', { scale: 1 }); } catch { /* game already gone */ }
      try { await bridge.invokeTool('stop_scene', {}); } catch { /* already stopped */ }
      if (existsSync(DET_FILE)) rmSync(DET_FILE);
    });

    it('advances an exact number of physics frames', async () => {
      const r = await bridge.invokeTool('step_frames', { frames: 10 }) as Record<string, unknown>;
      expect(r.frames).toBe(10);
      expect(r.mode).toBe('physics');
    }, 30000);

    it('returns as soon as a condition holds', async () => {
      const r = await bridge.invokeTool('await_condition', {
        condition: 'tree.get_frame() > 0', timeout_ms: 5000,
      }) as Record<string, unknown>;
      expect(r.met).toBe(true);
      expect(Number(r.frames_waited)).toBeGreaterThan(0);
    }, 30000);

    it('reports a condition that never holds as a result, not an error', async () => {
      // met:false is something a test asserts on. Returning an error here would
      // make "the thing never happened" indistinguishable from "the tool broke".
      const r = await bridge.invokeTool('await_condition', {
        condition: 'false', timeout_ms: 1000,
      }) as Record<string, unknown>;
      expect(r.met).toBe(false);
      expect(r).toHaveProperty('value');
    }, 30000);

    it('rejects an unparseable condition without taking the game down', async () => {
      // This is why the condition is an Expression and not a compiled GDScript:
      // building a GDScript from a bad string inside a running game KILLS it.
      // The first version of this test did exactly that and took 25s to report
      // a failure that looked like a timeout.
      const r = await bridge.invokeTool('await_condition', {
        condition: '(((', timeout_ms: 1000,
      }).catch((e: Error) => ({ error: e.message })) as Record<string, unknown>;
      expect(JSON.stringify(r)).toMatch(/parse/i);

      // The game must still be alive and answering: that is the actual assertion.
      const playing = await bridge.invokeTool('is_playing', {}) as Record<string, unknown>;
      expect(playing.playing).toBe(true);
      const still = await bridge.invokeTool('step_frames', { frames: 1 }) as Record<string, unknown>;
      expect(still.frames).toBe(1);
    }, 30000);

    // NOT covered here, deliberately: `game_eval` handed code that does not
    // compile KILLS the running game. Measured on 2026-07-27 — the call takes
    // ~24s and then every later runtime tool reports "runtime not connected".
    // The test is left out because it would burn 24s of CI to assert a bug we
    // already know about and would take the game down for everything after it.
    // See notes/LONGTERM.md; the fix needs the root cause of why
    // GDScript.reload() on bad source is fatal inside a running game, and
    // await_condition avoids it entirely by using Expression instead.

    it('reports an expression that parses but fails to evaluate, once', async () => {
      // Expression's grammar is permissive, so plenty of nonsense parses and
      // only fails on execute. That must be reported and dropped, not retried
      // every frame until the timeout.
      const r = await bridge.invokeTool('await_condition', {
        condition: 'nonexistent_thing.whatever()', timeout_ms: 5000,
      }).catch((e: Error) => ({ error: e.message })) as Record<string, unknown>;
      expect(JSON.stringify(r)).toMatch(/failed while evaluating/i);

      const playing = await bridge.invokeTool('is_playing', {}) as Record<string, unknown>;
      expect(playing.playing).toBe(true);
    }, 30000);

    it('seeds the RNG and says what it does not cover', async () => {
      const r = await bridge.invokeTool('seed_rng', { seed: 4242 }) as Record<string, unknown>;
      expect(r.seed).toBe(4242);
      expect(String(r.note)).toContain('RandomNumberGenerator');
    }, 30000);

    it('changes and restores the time scale', async () => {
      const slow = await bridge.invokeTool('time_scale', { scale: 0.5 }) as Record<string, unknown>;
      expect(slow.time_scale).toBeCloseTo(0.5);
      const back = await bridge.invokeTool('time_scale', { scale: 1 }) as Record<string, unknown>;
      expect(back.time_scale).toBeCloseTo(1);
    }, 30000);

    it('still advances frames while time is frozen', async () => {
      // The distinction that makes freezing useful: time_scale 0 stops
      // simulation without pausing the tree, so stepping still works and the
      // agent can inspect a frozen game frame by frame.
      await bridge.invokeTool('time_scale', { scale: 0 });
      const r = await bridge.invokeTool('step_frames', { frames: 3 }) as Record<string, unknown>;
      expect(r.frames).toBe(3);
      await bridge.invokeTool('time_scale', { scale: 1 });
    }, 30000);
  });
});

describe.skipIf(canRun)('E2E — real Godot editor process (skipped)', () => {
  it('skips: Godot binary missing or port 6505 already in use', () => {
    if (!godotAvailable) {
      console.log(`[e2e-godot] Skipped: Godot binary not found at ${GODOT_BIN}`);
    } else if (!portFree) {
      console.log(`[e2e-godot] Skipped: port ${BRIDGE_PORT} is already in use by another process (likely a real godot-mcp-server).`);
    }
    expect(canRun).toBe(false);
  });
});
