/**
 * End-to-end test that drives a REAL Godot process instead of mocking it.
 *
 * Every other test in this directory exercises the Node-side server in
 * isolation (unit tests calling into GodotBridge / tool handlers directly).
 * None of them ever prove that a tool call actually reaches the Godot
 * editor and mutates a project on disk. This test closes that gap for one
 * representative flow: create a scene, add a node to it, and confirm the
 * .tscn file on disk actually contains that node.
 *
 * Approach: editor-plugin headless, not the runtime autoload.
 * -------------------------------------------------------------------------
 * Editor-only tools like `add_node` and `create_scene` are handled by
 * addons/godot_mcp/tool_executor.gd, which only runs inside the EditorPlugin
 * (addons/godot_mcp/plugin.gd). The runtime autoload (mcp_runtime.gd) only
 * exposes a small "runtime" tool surface (query_runtime_node, send_input,
 * take_screenshot, ...) meant for inspecting a *running game*, not editing
 * scenes on disk — so it can't be used to test add_node.
 *
 * The open question was whether an EditorPlugin can run at all under
 * `--headless`. It can: Godot supports `--headless --editor`, which runs
 * the full editor (including plugin _enter_tree/_enable_plugin) without a
 * display server. This was confirmed manually before writing this test —
 * launching the fixture project with `--headless --editor` produces
 * "[Godot MCP] Plugin loading..." / "[MCP] Connected to server" in stdout.
 * So this test uses that mode directly.
 *
 * The addon's WebSocket client (mcp_client.gd) hardcodes ws://127.0.0.1:6505
 * with no override, so the bridge in this test must also listen on the
 * real DEFAULT_PORT rather than a private test port — that's the one way
 * this test can collide with a real godot-mcp-server already running on
 * this machine. If port 6505 is already taken, the test skips instead of
 * failing.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync, readFileSync, rmSync, cpSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { GodotBridge, createBridge } from '../godot-bridge.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// The full GUI exe, NOT the _console.exe sibling (a broken 0.2MB stub that dies with
// CreateProcess error 193). Set GODOT_BIN to your Godot executable to run this
// suite; without it, existsSync('') is false and everything below skips.
const GODOT_BIN = process.env.GODOT_BIN ?? '';
const FIXTURE_PROJECT = join(__dirname, 'fixtures', 'e2e-project');
const SCENE_PATH = 'res://e2e_test_scene.tscn';
const SCENE_FILE = join(FIXTURE_PROJECT, 'e2e_test_scene.tscn');

const CONNECT_TIMEOUT_MS = 30000;
const BRIDGE_PORT = 6505; // hardcoded in addons/godot_mcp/mcp_client.gd — not configurable

const godotAvailable = existsSync(GODOT_BIN);

/**
 * Port 6505 is hardcoded into the addon and can't be overridden, so if a
 * real godot-mcp-server (e.g. the user's own editor session) already owns
 * it, we can't bind our test bridge there. Rather than fail the suite in
 * that case, we detect it up front and skip with a clear reason.
 */
async function isPortFree(port: number): Promise<boolean> {
  const probe = createBridge(port);
  try {
    await probe.start();
    probe.stop();
    return true;
  } catch {
    return false;
  }
}

/**
 * Copy the repo's addon over the fixture's own copy before the editor starts.
 *
 * The fixture project carries its own `addons/godot_mcp`, and the editor this
 * suite spawns loads THAT one. Without this sync the tests silently exercise
 * whatever was in the fixture last time — which happened while writing these
 * tests: a just-fixed clobbering bug still failed here because the editor was
 * running the stale copy, which reads exactly like "the fix didn't work".
 * scripts/test-gd.ps1 and CI already mirror the addon for the same reason; the
 * Node suite has to do it too or it is testing a different codebase.
 */
function syncAddonIntoFixture(): void {
  const source = join(__dirname, '..', '..', '..', 'addons', 'godot_mcp');
  const dest = join(FIXTURE_PROJECT, 'addons', 'godot_mcp');
  if (!existsSync(source)) return;
  rmSync(dest, { recursive: true, force: true });
  cpSync(source, dest, {
    recursive: true,
    // .uid files are per-project and regenerated by the editor; copying them
    // across makes Godot complain about duplicate UIDs.
    filter: (src) => !src.endsWith('.uid'),
  });
}

const portFree = godotAvailable ? await isPortFree(BRIDGE_PORT) : false;
const canRun = godotAvailable && portFree;

describe.skipIf(!canRun)('E2E — real Godot editor process', () => {
  let bridge: GodotBridge;
  let godotProcess: ChildProcess | null = null;

  beforeAll(async () => {
    if (existsSync(SCENE_FILE)) rmSync(SCENE_FILE);
    syncAddonIntoFixture();

    bridge = createBridge(BRIDGE_PORT);
    await bridge.start();

    godotProcess = spawn(
      GODOT_BIN,
      ['--headless', '--editor', '--path', FIXTURE_PROJECT],
      { stdio: 'ignore' }
    );

    await new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => {
        reject(new Error(`Godot editor did not connect to the bridge within ${CONNECT_TIMEOUT_MS}ms`));
      }, CONNECT_TIMEOUT_MS);

      const check = setInterval(() => {
        if (bridge.isConnected()) {
          clearInterval(check);
          clearTimeout(timer);
          resolve();
        }
      }, 250);
    });

    // CRITICAL: confirm we're talking to the fixture project and not to
    // somebody's real one.
    //
    // The addon hardcodes port 6505, so ANY Godot editor already open on this
    // machine will reconnect to whatever is listening there — including the
    // bridge this test just started. The isPortFree() check above only proves
    // the port was free when the suite loaded; it cannot stop an existing
    // editor from attaching a moment later. Without this guard the mutation
    // tests below run `create_scene`/`add_node`/`remove_node` against that
    // editor's project. That has actually happened, and it wrote a scene file
    // into a real game project.
    const connectedPath = bridge.getStatus().projectPath ?? '';
    const expected = FIXTURE_PROJECT.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
    const actual = connectedPath.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
    if (actual !== expected) {
      throw new Error(
        `Refusing to run: the editor on port ${BRIDGE_PORT} has "${connectedPath}" open, not the test fixture ` +
        `("${FIXTURE_PROJECT}"). Close other Godot editors before running the e2e suite — these tests create and ` +
        `delete scenes in whatever project is connected.`
      );
    }
  }, CONNECT_TIMEOUT_MS + 5000);

  afterAll(() => {
    godotProcess?.kill();
    godotProcess = null;
    bridge?.stop();
    if (existsSync(SCENE_FILE)) rmSync(SCENE_FILE);
  });

  it('connects a real Godot editor over the WebSocket bridge', () => {
    expect(bridge.isConnected()).toBe(true);
  });

  it('creates a scene, adds a node, and persists it to disk', async () => {
    const createResult = await bridge.invokeTool('create_scene', {
      scene_path: SCENE_PATH,
      root_node_type: 'Node2D',
      root_node_name: 'Root',
    }) as Record<string, unknown>;
    expect(createResult.scene_path ?? SCENE_PATH).toBeTruthy();
    expect(existsSync(SCENE_FILE)).toBe(true);

    await bridge.invokeTool('add_node', {
      scene_path: SCENE_PATH,
      node_name: 'E2ESprite',
      node_type: 'Sprite2D',
      parent_path: '.',
    });

    const contents = readFileSync(SCENE_FILE, 'utf-8');
    expect(contents).toContain('E2ESprite');
    expect(contents).toContain('Sprite2D');
  }, 15000);

  it('removes the node it added', async () => {
    const result = await bridge.invokeTool('remove_node', {
      scene_path: SCENE_PATH,
      node_path: 'E2ESprite',
    }) as Record<string, unknown>;
    expect(result).toBeTruthy();

    const contents = readFileSync(SCENE_FILE, 'utf-8');
    expect(contents).not.toContain('E2ESprite');
  }, 15000);

  // -------------------------------------------------------------------------
  // Live-scene harness
  // -------------------------------------------------------------------------
  // Everything above drives the DISK path. The live path — the scene is open in
  // the editor, so tools mutate the editor's real node tree instead of a loaded
  // copy — is the half that carries the project's hardest invariants, and until
  // now nothing tested it automatically:
  //
  //   * `_discard_scene` is a NO-OP on a live scene, so a tool that writes and
  //     then fails validation leaves those writes applied while reporting
  //     failure. That exact shape has been found six times.
  //   * A live edit must NOT touch the .tscn on disk (that's the anti-clobber
  //     guarantee the README leads with).
  //
  // These run against a real headless editor with the scene actually open.
  describe('live scene (open in the editor)', () => {
    const LIVE_SCENE = 'res://e2e_live_scene.tscn';
    const LIVE_FILE = join(FIXTURE_PROJECT, 'e2e_live_scene.tscn');

    beforeAll(async () => {
      if (existsSync(LIVE_FILE)) rmSync(LIVE_FILE);
      await bridge.invokeTool('create_scene', {
        scene_path: LIVE_SCENE,
        root_node_type: 'Node2D',
        root_node_name: 'Root',
      });
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE,
        node_name: 'Body',
        node_type: 'CharacterBody2D',
        parent_path: '.',
      });
      // set_material_3d needs a node that actually has material_override, or it
      // fails on the type check before writing anything and the case proves
      // nothing.
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE,
        node_name: 'Mesh',
        node_type: 'MeshInstance3D',
        parent_path: '.',
      });
      // Nodes the clobber cases need: a Sprite2D for texture/material, a Control
      // for anchor presets.
      const EXTRA_NODES = [
        ['Sprite', 'Sprite2D'],
        ['Panel', 'Control'],
        ['Shape', 'CollisionShape2D'], // the node that actually carries `shape`
      ] as const;
      for (const [name, type] of EXTRA_NODES) {
        await bridge.invokeTool('add_node', {
          scene_path: LIVE_SCENE, node_name: name, node_type: type, parent_path: '.',
        });
      }
      // connect_signal refuses unless the receiving script really declares the
      // method, so the probe script declares it and is attached to the receiver.
      await bridge.invokeTool('create_script', {
        path: 'res://e2e_clobber_probe.gd',
        content: 'extends Node2D\nfunc _on_body_ready() -> void:\n\tpass\n',
      });
      await bridge.invokeTool('attach_script', {
        scene_path: LIVE_SCENE, node_path: '.', script_path: 'res://e2e_clobber_probe.gd',
      });
      await bridge.invokeTool('create_scene', {
        scene_path: 'res://e2e_clobber_child.tscn',
        root_node_type: 'Node2D',
        root_node_name: 'Child',
      });
      // A .tres texture, not a .png: an image needs Godot's import step, which a
      // freshly-spawned headless editor has not necessarily finished, and the
      // texture case would fail for a reason that has nothing to do with it.
      await bridge.invokeTool('create_resource', {
        resource_type: 'GradientTexture1D',
        resource_path: 'res://e2e_clobber_tex.tres',
      });
      // These three files were written a moment ago through the bridge, so the
      // editor's filesystem doesn't know about them yet and load() fails —
      // `instance_scene` came back with "Failed to instantiate scene" on a cold
      // CI runner while passing locally purely on timing. Rescan and wait for the
      // scene to actually be loadable rather than sleeping a guessed interval.
      // A scan may already be running right after those writes, and rescan
      // rejects rather than queueing — so the request itself is best-effort. The
      // poll below is the actual wait: it stops when the scene is loadable.
      await bridge.invokeTool('rescan_filesystem', {}).catch(() => null);
      for (let i = 0; i < 40; i++) {
        const probe = await bridge.invokeTool('read_scene', {
          scene_path: 'res://e2e_clobber_child.tscn',
        }).catch(() => null) as Record<string, unknown> | null;
        if (probe && !probe.error) break;
        await new Promise(r => setTimeout(r, 250));
      }
      // From here on the scene is OPEN, so every tool below takes the live path.
      await bridge.invokeTool('open_in_godot', { path: LIVE_SCENE });
    }, 30000);

    afterAll(() => {
      if (existsSync(LIVE_FILE)) rmSync(LIVE_FILE);
      for (const extra of [
        'e2e_clobber_probe.gd', 'e2e_clobber_probe.gd.uid',
        'e2e_clobber_child.tscn', 'e2e_clobber_tex.tres',
      ]) {
        const f = join(FIXTURE_PROJECT, extra);
        if (existsSync(f)) rmSync(f);
      }
    });

    it('edits the live tree without touching the file on disk', async () => {
      const before = readFileSync(LIVE_FILE, 'utf-8');

      await bridge.invokeTool('add_raycast', {
        scene_path: LIVE_SCENE,
        parent_path: '.',
        node_name: 'LiveRay',
        dimension: '2D',
      });

      const dump = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(dump).toContain('LiveRay');
      // The whole point: the agent's edit lives in the editor, unsaved, so the
      // developer's own unsaved work is never overwritten.
      expect(readFileSync(LIVE_FILE, 'utf-8')).toBe(before);
    }, 20000);

    it('undoes a live edit through the editor history', async () => {
      const undone = await bridge.invokeTool('undo_last', {}) as Record<string, unknown>;
      expect(String(undone.message ?? '')).toContain('LiveRay');

      const dump = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(dump).not.toContain('LiveRay');
    }, 20000);

    // The regression net for the six-times bug. Each case takes several settable
    // values and rejects the LAST one, so a tool that writes as it goes leaves
    // the earlier writes behind.
    //
    // Each case names its own `probe`: a LIVE-AWARE read of the state the tool
    // touches. Comparing scene_tree_dump alone is not enough and this was proven
    // the hard way — the first version of this harness compared only the tree,
    // and passed with the bug deliberately reintroduced into set_physics_layers,
    // because a changed property doesn't show up in a structural dump.
    const PARTIAL_WRITE_CASES: Array<{
      tool: string;
      args: Record<string, unknown>;
      probe: { tool: string; args: Record<string, unknown> };
    }> = [
      {
        tool: 'set_physics_layers',
        // Valid layer, then a collision_mask naming a layer that doesn't exist.
        args: { node_path: 'Body', collision_layer: 3, collision_mask: ['no_such_layer_xyz'] },
        probe: { tool: 'get_collision_info', args: { node_path: 'Body' } },
      },
      {
        tool: 'set_material_3d',
        // Applies metallic/roughness, then rejects the emission colour.
        args: { node_path: 'Mesh', metallic: 0.5, roughness: 0.5, emission_color: 'not-a-color' },
        probe: { tool: 'get_scene_node_properties', args: { node_path: 'Mesh' } },
      },
      {
        tool: 'setup_environment',
        // This one CREATES a WorldEnvironment node before validating colours, so
        // the structural dump is the right probe here.
        args: { sky_top_color: { r: 1, g: 1, b: 1, a: 1 }, fog_enabled: true, sky_horizon_color: 'not-a-color' },
        probe: { tool: 'scene_tree_dump', args: {} },
      },
    ];

    it.each(PARTIAL_WRITE_CASES)(
      '$tool leaves nothing behind when a later argument is invalid',
      async ({ tool, args, probe }) => {
        const readState = async () => JSON.stringify(
          await bridge.invokeTool(probe.tool, { scene_path: LIVE_SCENE, ...probe.args }),
        );

        const fileBefore = readFileSync(LIVE_FILE, 'utf-8');
        const treeBefore = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
        const stateBefore = await readState();

        let failed = false;
        try {
          const res = await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }) as Record<string, unknown>;
          failed = res?.ok === false || typeof res?.error === 'string';
        } catch {
          failed = true; // an error result surfaces as a throw through the bridge
        }
        expect(failed, `${tool} was expected to reject its last argument`).toBe(true);

        expect(await readState(), `${tool} left a partial write (probe: ${probe.tool})`).toBe(stateBefore);
        expect(JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }))).toBe(treeBefore);
        expect(readFileSync(LIVE_FILE, 'utf-8')).toBe(fileBefore);
      },
      25000,
    );

    // The anti-clobber guarantee, which is the first thing the README claims.
    //
    // A tool that loads the scene from disk, mutates the copy and saves it does
    // two destructive things at once when the scene is open: it discards
    // whatever is unsaved in the editor, and the reload that follows the save
    // wipes the live tree. Confirmed by hand against a real project before this
    // test existed — an `attach_script` call destroyed an unsaved node that was
    // sitting in the open scene.
    //
    // `holder` is a node added to the LIVE tree and never saved. Any tool that
    // round-trips through disk will lose it.
    // Every scene-mutating tool that reaches the disk. Arguments are chosen to
    // SUCCEED: a tool that errors early would never load the scene, so the test
    // would pass without proving anything.
    const CLOBBER_TOOLS: Array<{ tool: string; args: Record<string, unknown> }> = [
      { tool: 'attach_script', args: { node_path: 'Body', script_path: 'res://e2e_clobber_probe.gd' } },
      { tool: 'detach_script', args: { node_path: 'Body' } },
      { tool: 'set_node_groups', args: { node_path: 'Body', groups: ['e2e_group'] } },
      { tool: 'set_collision_shape', args: { node_path: 'Shape', shape_type: 'RectangleShape2D' } },
      { tool: 'set_sprite_texture', args: { node_path: 'Sprite', texture_type: 'FromPath', texture_params: { path: 'res://e2e_clobber_tex.tres' } } },
      { tool: 'set_mesh', args: { node_path: 'Mesh', mesh_type: 'BoxMesh' } },
      { tool: 'set_material', args: { node_path: 'Mesh', material_type: 'StandardMaterial3D' } },
      { tool: 'set_anchor_preset', args: { node_path: 'Panel', preset: 'full_rect' } },
      { tool: 'snap_node_to_grid', args: { node_path: 'Mesh', grid_size: 16 } },
      { tool: 'set_scene_node_property', args: { node_path: 'Body', property_name: 'visible', value: false } },
      { tool: 'instance_scene', args: { parent_path: '.', instance_path: 'res://e2e_clobber_child.tscn', instance_name: 'Inst' } },
      { tool: 'connect_signal', args: { from_node: 'Body', signal: 'ready', to_node: '.', method: '_on_body_ready' } },
      { tool: 'disconnect_signal', args: { from_node: 'Body', signal: 'ready', to_node: '.', method: '_on_body_ready' } },
      // Runs after set_collision_shape, which is what puts a shape on Shape.
      { tool: 'set_resource_property', args: { node_path: 'Shape', resource_path: 'shape', property_name: 'size', value: { x: 16, y: 16 } } },
    ];

    it.each(CLOBBER_TOOLS)('$tool does not destroy unsaved work in the open scene', async ({ tool, args }) => {
      const holder = `Unsaved_${tool}`;
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE, node_name: holder, node_type: 'Node2D', parent_path: '.',
      });
      const withHolder = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(withHolder, 'setup failed: the unsaved node never reached the live tree').toContain(holder);

      // The call must actually do its job. Tolerating an error here would let a
      // tool that bails out before touching the scene pass vacuously.
      const res = await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }) as Record<string, unknown>;
      expect(res?.error, `${tool} failed, so this case proves nothing: ${JSON.stringify(res)}`).toBeUndefined();

      const after = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(after, `${tool} clobbered unsaved live work`).toContain(holder);

      await bridge.invokeTool('remove_node', { scene_path: LIVE_SCENE, node_path: holder }).catch(() => {});
    }, 25000);

    // Reads have to see the live tree too. A tool that loads from disk reports
    // the last-SAVED state, so an agent that edits and then reads back gets
    // stale values with no way to tell — it looks like the edit silently failed.
    const LIVE_READ_TOOLS: Array<{ tool: string; args: Record<string, unknown>; expect: string }> = [
      { tool: 'read_scene', args: {}, expect: 'ReadProbe' },
      { tool: 'get_scene_hierarchy', args: {}, expect: 'ReadProbe' },
      { tool: 'get_scene_node_properties', args: { node_path: 'ReadProbe' }, expect: 'position' },
      { tool: 'get_node_groups', args: { node_path: 'ReadProbe' }, expect: 'read_probe_group' },
      { tool: 'find_nodes_in_group', args: { group: 'read_probe_group' }, expect: 'ReadProbe' },
    ];

    it.each(LIVE_READ_TOOLS)('$tool reads the live tree, not the last save', async ({ tool, args, expect: needle }) => {
      // Added and grouped only in the editor — never saved to the .tscn.
      await bridge.invokeTool('add_node', {
        scene_path: LIVE_SCENE, node_name: 'ReadProbe', node_type: 'Node2D', parent_path: '.',
      });
      await bridge.invokeTool('set_node_groups', {
        scene_path: LIVE_SCENE, node_path: 'ReadProbe', groups: ['read_probe_group'],
      });
      expect(readFileSync(LIVE_FILE, 'utf-8'), 'setup: the probe must NOT be on disk').not.toContain('ReadProbe');

      const out = JSON.stringify(await bridge.invokeTool(tool, { scene_path: LIVE_SCENE, ...args }));
      expect(out, `${tool} returned last-saved state instead of the live tree`).toContain(needle);

      await bridge.invokeTool('remove_node', { scene_path: LIVE_SCENE, node_path: 'ReadProbe' }).catch(() => {});
    }, 25000);

    it('reverts a whole batch when one operation fails', async () => {
      const treeBefore = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));

      try {
        await bridge.invokeTool('batch_scene_edit', {
          scene_path: LIVE_SCENE,
          stop_on_error: true,
          operations: [
            { op: 'add_node', node_name: 'BatchLiveA', node_type: 'Node2D', parent_path: '.' },
            { op: 'add_node', node_name: 'BatchLiveB', node_type: 'Node2D', parent_path: '.' },
            { op: 'remove_node', node_path: 'NoSuchNode' },
          ],
        });
      } catch {
        // expected: the batch reports failure
      }

      // "batch discarded, nothing saved" has to be true on the live path too,
      // where _discard_scene cannot undo anything.
      const treeAfter = JSON.stringify(await bridge.invokeTool('scene_tree_dump', { scene_path: LIVE_SCENE }));
      expect(treeAfter).toBe(treeBefore);
    }, 25000);
  });
});

describe.skipIf(canRun)('E2E — real Godot editor process (skipped)', () => {
  it('skips: Godot binary missing or port 6505 already in use', () => {
    if (!godotAvailable) {
      console.log(`[e2e-godot] Skipped: Godot binary not found at ${GODOT_BIN}`);
    } else if (!portFree) {
      console.log(`[e2e-godot] Skipped: port ${BRIDGE_PORT} is already in use by another process (likely a real godot-mcp-server).`);
    }
    expect(canRun).toBe(false);
  });
});
